#!/bin/bash

echo "<<<app-docker>>>"
info=$(docker info 2> /dev/null | grep "Containers:\|Running:\|Paused:\|Stopped:\|Images:")
echo $info | awk '{print $2}'
echo $info | awk '{print $4}'
echo $info | awk '{print $6}'
echo $info | awk '{print $8}'
echo $info | awk '{print $10}'
